# RAAQA — Read Alignment-based Assembly Quality Assessment

name: raaqa
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python>=3.10

  # --- Core mapq_softc module dependency ---
  - pysam>=0.22.0

  # --- Visualisation module dependencies ---
  # - matplotlib-base
  # - pandas
  # - numpy

  # --- Preprocessing tools ---
  # Required to generate inputs for mapq_softclip module:
  - samtools>=1.17
  # Required to generate inputs for hese module:
  #